# Generated by Django 6.1.1 on 2026-09-10 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=0, help_text='Cost in coins to unlock (0 = free/starter)')),
                ('color_primary', models.CharField(default='#00e5ff', help_text='Primary hex color', max_length=32)),
                ('color_secondary', models.CharField(default='#ff007f', help_text='Secondary/accent hex color', max_length=32)),
                ('speed_multiplier', models.FloatField(default=1.0, help_text='Base speed modifier (e.g. 1.05 = +5% speed)')),
                ('coin_multiplier', models.FloatField(default=1.0, help_text='Coin value modifier (e.g. 1.2 = +20% coins)')),
                ('icon_emoji', models.CharField(default='🏃', max_length=16)),
                ('sprite_key', models.CharField(default='char_runner', max_length=64)),
                ('is_default', models.BooleanField(default=False, help_text='Is this character unlocked by default for new players?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PowerUpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('power_type', models.CharField(choices=[('magnet', 'Magnet (Coin Suction)'), ('shield', 'Shield (Hit Absorption)'), ('speed_boost', 'Speed Boost (Nitro Runner)'), ('multiplier', '2x Score Multiplier')], max_length=32, unique=True)),
                ('duration_seconds', models.FloatField(default=10.0)),
                ('spawn_weight', models.FloatField(default=1.0, help_text='Relative spawn frequency weight')),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(default='⚡', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_coins', models.PositiveIntegerField(default=0)),
                ('high_score', models.PositiveIntegerField(default=0)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_distance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_players', to='game_api.character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, default='Guest Runner', max_length=50)),
                ('score', models.PositiveIntegerField(default=0)),
                ('coins_collected', models.PositiveIntegerField(default=0)),
                ('distance_traveled', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_api.character')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_by', to='game_api.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'character')},
            },
        ),
    ]
